name: Build and Push Multi-Arch Docker Image (kubernetes_mcp_server)

on:
  workflow_dispatch:
    inputs:
      mcp_version:
        description: 'kubernetes-mcp-server release version (e.g. v1.2.3 or latest)'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      MCP_VERSION: ${{ github.event.inputs.mcp_version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push multi-arch image
      uses: docker/build-push-action@v5
      with:
        context: ./kubernetes_mcp_server
        file: ./kubernetes_mcp_server/Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: |
          MCP_VERSION=${{ env.MCP_VERSION }}
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/mcp-server:${{ env.MCP_VERSION }}
          ghcr.io/${{ github.repository }}/mcp-server:latest
