name: Build and Push Multi-Arch Docker Image (kubernetes_agent)

on:
  workflow_dispatch:
    inputs:
      agent_version:
        description: 'kubernetes_agent release version (e.g. v1.2.3 or latest)'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      AGENT_VERSION: ${{ github.event.inputs.agent_version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push multi-arch image
      uses: docker/build-push-action@v5
      with:
        context: ./kubernetes_agent
        file: ./kubernetes_agent/Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: |
          AGENT_VERSION=${{ env.AGENT_VERSION }}
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/kubernetes-agent:${{ env.AGENT_VERSION }}
          ghcr.io/${{ github.repository }}/kubernetes-agent:latest
